sudo: false

language: c

matrix:
  include:
    - env: FLAGS="" ARGS=""
      compiler: ": #stack default"
      addons: {apt: {packages: [libgmp-dev]}}
    - env: FLAGS="" ARGS="--stack-yaml=stack-previous.yaml"
      compiler: ": #stack previous"
      addons: {apt: {packages: [libgmp-dev]}}
    - env: FLAGS="" ARGS="--stack-yaml=stack-liquidhaskell.yaml" LIQUIDHASKELL=1
      compiler: ": #stack LiquidHaskell"
      addons:
        apt:
          sources:
            - sourceline: "ppa:hvr/z3"
          packages: [libgmp-dev, z3]

before_install:
- unset CC
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
- stack $ARGS --install-ghc --no-terminal build $FLAGS --pedantic --haddock --no-haddock-deps --test --bench
- |
  if [ "$LIQUIDHASKELL" ]; then
    stack $ARGS build liquidhaskell
    stack $ARGS exec -- liquid src/TSA.hs
  fi

cache:
  directories:
  - $HOME/.stack
