name:                tsa
version:             0.1.0.0
synopsis:            Time Series Analysis
#description:
homepage:            https://github.com/dzhus/tsa#readme
license:             BSD3
author:              Dmitry Dzhus
maintainer:          dima@dzhus.org
copyright:           2018 Dmitry Dzhus
category:            Web

extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  - -Wall
  - -Wcompat

flags:
  ihaskell:
    description: Build functions for IHaskell support
    manual: true
    default: false

library:
  source-dirs:      src
  dependencies:
    - base < 5
    - attoparsec
    - csv-conduit
    - lens
    - statistics
    - vector
  when:
    - condition: flag(ihaskell)
      cpp-options: -DWITH_IHASKELL
      dependencies:
        - Chart
        - ihaskell-charts
